version: "3.8"
services:
  app:
    image: node:18
    container_name: BackEnd-docker
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: 
    - chmod u+x package.json
    - chmod g+x package.json
    - npm start

