services:
  app:
    image: node:18
    container_name: BackEnd-docker
    restart: always
    # working_dir: /home/dani/Monopoly/Back-End
    volumes:
      - ./../Back-End:./app
    command: 
      - cd app
      - npm start